/* 
  This file is generated by create-react-app.
  It is used for the app's metadata and PWA configuration.
  Update the theme-color and background-color to match your brand.
*/

const config = {
  production: process.env.NODE_ENV === 'production',
  apiUrl: process.env.NODE_ENV === 'production' 
    ? 'https://api.adharashadja.com' 
    : 'http://localhost:5000'
};

export default config;
