import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    langName: 'English',
    nav: {
      onlineClasses: 'Online Classes',
      about: 'About Us',
      guru: 'Our Guru',
      courses: 'Categories',
      gallery: 'Gallery',
      achievements: 'Achievements',
      certifications: 'Certifications',
      community: 'Community',
      reviews: 'Reviews',
      contact: 'Contact Us',
      register: 'Register Now'
    },
    hero: {
      title: 'ADHARA SHADJA Gurukula',
      subtitle: 'Preserving and Teaching the Tradition of Indian Classical Music',
      registerBtn: 'Register for Online Music Classes',
      watchBtn: 'Watch Performance'
    },
    about: {
      title: 'About ADHARA SHADJA',
      subtitle: 'Preserving Musical Heritage',
      p1: 'ADHARA SHADJA Gurukula is dedicated to teaching and preserving Indian classical music traditions through structured training and personal mentorship. Established in the rural area of Hirehadda in North Kanara, Karnataka, our organization operates with the primary motive of teaching Indian Classical Music to students who are passionate about this ancient art form.',
      p2: 'We offer both online and offline classes, making classical music education accessible to students across the region and beyond. Our programs are designed to nurture talent, preserve the authentic tradition, and create a community of music lovers who appreciate the depth and beauty of Hindustani classical music.',
      missionTitle: 'Our Mission',
      missionText: 'To preserve, teach, and promote the tradition of Indian Classical Music through structured training, mentorship, and community engagement while maintaining the authenticity and essence of this ancient art form.',
      expertTraining: 'Expert Training',
      expertTrainingDesc: 'Learn from experienced gurus with decades of practice',
      curriculum: 'Structured Curriculum',
      curriculumDesc: 'Step-by-step learning path from basics to advanced raags',
      flexibility: 'Flexible Learning',
      flexibilityDesc: 'Online and offline options to suit your schedule'
    },
    guru: {
      title: 'Meet Our Guru',
      subtitle: 'Learn from a Master',
      name: 'Shri Vinayak Hegde Hirehadda',
      role: 'Founder & Guru',
      experience: 'Experience',
      experienceDesc: 'Multiple decades of training and performance',
      background: 'Background',
      backgroundDesc: 'Senior disciple of Pt. Ganapati Bhat Hasanagi',
      expertise: 'Expertise',
      expertiseDesc: 'Hindustani Classical Vocal Music',
      aboutGuruTitle: 'About Shri Vinayak Hegde',
      aboutGuruText: 'Shri Vinayak Hegde Hirehadda is a multi-talented musician who has dedicated his life to the preservation and teaching of Indian Classical Music. He has given numerous performances throughout Karnataka and traveled extensively with his guru, performing across India and internationally in countries like Dubai and Abu Dhabi.',
      philosophyTitle: 'Teaching Philosophy',
      philosophyText: '"Music is not just an art form; it is a way of life. Through dedicated practice and authentic learning from a living guru, one can master the nuances of this sacred tradition and contribute to its preservation for future generations."'
    },
    courses: {
      title: 'Learning Categories',
      subtitle: 'Indian Classical Vocal Training',
      loading: 'Loading categories...',
      contactFees: 'Contact us for fees and batch timings',
      enrollBtn: 'Register Now',
      juniorTitle: 'Junior Category',
      juniorLevel: 'Beginner Level',
      seniorTitle: 'Senior Category',
      seniorLevel: 'Intermediate Level',
      vidwathTitle: 'Vidwath Category',
      vidwathLevel: 'Advanced Level',
      specialGenresTitle: 'Special Repertoire & Music Forms',
      specialGenresSubtitle: 'We also teach Devotional Classical Music, Ghazals, and Thumris',
      genreDevotional: 'Devotional Classical Music',
      genreDevotionalDesc: 'Bhajans, Dasarpada, Vachana, Abhangs, and Stotras taught with authentic classical raag foundations',
      genreGhazals: 'Ghazals',
      genreGhazalsDesc: 'Expressive Urdu and Hindi Ghazal renditions focusing on poetry nuance, vocal modulation, and emotion',
      genreThumri: 'Thumris & Dadra',
      genreThumriDesc: 'Rich semi-classical compositions emphasizing romantic aesthetics, bol-banaav, and light classical raags'
    },
    facilities: {
      title: 'FACILITIES FOR STUDENTS',
      examPrepTitle: 'EXAM PREPARATION',
      examPrepDesc: 'Students can appear for KSEE Board Bangalore and ABGM music examinations',
      scholarshipTitle: 'SCHOLARSHIP SUPPORT',
      scholarshipDesc: 'Eligible students can apply for scholarships from state, central and NGOs'
    },
    achievements: {
      title: 'Our Achievements',
      subtitle: 'Milestones & Recognition',
      studentsTrained: 'Students Trained',
      studentsTrainedDesc: 'Over 500+ students guided in classical vocal music',
      performances: 'Concert Performances',
      performancesDesc: '100+ prestigious stage performances across India and abroad',
      awards: 'Awards & Honors',
      awardsDesc: 'Recognized by multiple cultural and classical institutions',
      experienceYears: 'Years of Tradition',
      experienceYearsDesc: 'Decades of authentic Guru-Shishya tradition',
      highlightsTitle: 'Key Highlights',
      h1: '✓ Prestigious lineage of classical music training',
      h2: '✓ Trained numerous students in Hindustani classical music',
      h3: '✓ Regular music programs and concerts in Karnataka and beyond',
      h4: '✓ Alumni performing in national and international platforms'
    },
    certifications: {
      title: 'Music Certifications & Board Exams',
      subtitle: 'Gandharva Mahavidyalaya Preparation & ADHARA Shadja Trust Certificates',
      intro: 'We provide structured training aligned with the Gandharva Maha Vidyalaya syllabus. We prepare students for various prestigious music board exams and grant recognized certificates from our ADHARA Shadja Gurukula Trust.',
      benefitsTitle: 'Key Academic & Certification Benefits',
      b1: '✓ Teaching aligned with Akhil Bharatiya Gandharva Mahavidyalaya syllabus',
      b2: '✓ Thorough coaching for Junior, Senior & Vidwath examinations',
      b3: '✓ Authorized institutional certificates awarded by ADHARA Shadja Trust',
      b4: '✓ Prepares students for stage recitals, concerts and teaching careers',
      c1_title: 'Junior Category Certificate (Beginner)',
      c1_desc: 'Foundational certification covering swaras, alankars and primary raags under Gandharva syllabus',
      c2_title: 'Senior Category Certificate (Intermediate)',
      c2_desc: 'Proficiency in raag vistar, taal systems, bandishes, and Senior board exam readiness',
      c3_title: 'Vidwath Category Certificate (Advanced)',
      c3_desc: 'Mastery over complex ragas, vilambit-drut khayals, improvisation, and concert performance capability',
      c4_title: 'ADHARA Shadja Trust Teaching & Merit Certificate',
      c4_desc: 'Honors students who demonstrate exceptional dedication and capability to teach and propagate classical music'
    },
    gallery: {
      title: 'Gallery & Media',
      subtitle: 'Documentaries, Performances, Baithaks & Guruvandana',
      viewFullBtn: 'Open Full Gallery →',
      exploreHeading: 'Explore Gurukula Moments',
      documentaryTitle: 'Documentary of ADHARA Shadja Gurukula',
      documentaryDesc: 'Journey, traditions, and musical heritage of our Gurukula in Hirehadda',
      studentPerfTitle: 'Classical Performance by Student',
      studentPerfDesc: 'Student displaying raga performance and vocal mastery',
      teachingSessionTitle: 'Gurukula Music Teaching Session',
      teachingSessionDesc: 'Interactive Guru-Shishya training in traditional classroom',
      guruPerfTitle: 'Classical Performance by Shri Vinayak Hegde',
      guruPerfDesc: 'Guru rendering soulful Hindustani classical ragas',
      baithakTitle: 'Monthly Baithak - Sangeetha Sammelana',
      baithakDesc: 'Monthly intimate classical gathering and riyaz session at Gurukula',
      guruvandanaTitle: 'Guruvandana Utsava & Felicitation Program',
      guruvandanaDesc: 'Homage and grand celebrations honoring the sacred Guru tradition',
      studentConcertTitle: 'Student Concert & Recitals',
      traditionalPerfTitle: 'Traditional Gurukula Event',
      uploadBtn: '+ Upload Photo / Video',
      filterAll: 'All Media',
      filterDocumentary: 'Documentary',
      filterPerformances: 'Performances',
      filterTeaching: 'Teaching Sessions',
      filterBaithak: 'Monthly Baithaks',
      filterGuruvandana: 'Guruvandana Program',
      filterUploaded: 'Admin Uploads',
      uploadModalTitle: 'Upload to Gurukula Gallery (Authorized)',
      mediaType: 'Media Type',
      typePhoto: 'Photo (Image Upload)',
      typeVideo: 'YouTube Video',
      mediaTitle: 'Title *',
      mediaCategory: 'Category *',
      mediaDescription: 'Description',
      mediaYoutubeUrl: 'YouTube URL (e.g., https://youtu.be/...)',
      mediaFile: 'Choose Image File',
      submitUpload: 'Add to Gallery',
      cancel: 'Cancel',
      backToHome: '← Back to Main Page',
      noItems: 'No items found in this category.',
      successUpload: 'Media added successfully to gallery!',
      authRequiredTitle: 'Authorized Personnel Only',
      authRequiredDesc: 'Only authorized ADHARA SHADJA administrators and gurus can upload or modify media.',
      enterPasscode: 'Enter Admin Passcode',
      passcodePlaceholder: 'Security Passcode (Default: adhara@2024)',
      verifyLoginBtn: 'Verify & Unlock Upload',
      invalidPasscode: 'Invalid passcode! Please enter the authorized administrator key.',
      adminLoggedInBadge: 'Authorized Admin Active',
      logoutBtn: 'Logout Admin',
      adminPasscodeHint: 'Admin passcode is required to prevent unauthorized uploads.'
    },
    registration: {
      title: 'Student Registration',
      subtitle: 'Begin Your Musical Journey With Us',
      firstName: 'First Name *',
      lastName: 'Last Name *',
      email: 'Email Address *',
      phone: 'Phone Number *',
      age: 'Age *',
      experience: 'Prior Music Experience / Category',
      expBeginner: 'Junior Category (Beginner / Fresh learner)',
      expIntermediate: 'Senior Category (Intermediate / 1-2 years experience)',
      expAdvanced: 'Vidwath Category (Advanced / 3+ years experience)',
      selectCourse: 'Select Category / Genre *',
      address: 'Address *',
      city: 'City *',
      state: 'State *',
      country: 'Country *',
      submitBtn: 'Submit Registration',
      submitting: 'Submitting...',
      successMsg: 'Registration successful! We will contact you soon with class and batch details.',
      placeholderName: 'Your first name',
      placeholderLastName: 'Your last name',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'Your phone number',
      placeholderAge: 'Your age',
      placeholderAddress: 'Street address',
      placeholderCity: 'City'
    },
    community: {
      title: 'Join Our Community',
      subtitle: 'Connect with Music Lovers & Learners',
      intro: 'Be part of a vibrant community of classical music enthusiasts, students, and professionals. Share your passion, learn from others, and grow together in your musical journey.',
      forums: 'Online Forums',
      forumsDesc: 'Discuss music concepts, share experiences, and get tips from fellow learners',
      events: 'Regular Events',
      eventsDesc: 'Attend virtual concerts, workshops, and master classes by renowned musicians',
      networking: 'Networking',
      networkingDesc: 'Connect with music professionals and potential collaborators',
      resources: 'Resource Sharing',
      resourcesDesc: 'Access to exclusive learning materials and recordings',
      followUs: 'Follow Us On Social Media',
      supportMission: 'Support Our Mission',
      supportDesc: 'Help us preserve and promote Indian Classical Music traditions',
      contributeBtn: 'Contribute Now',
      processing: 'Processing...'
    },
    reviews: {
      title: 'Student Reviews',
      subtitle: 'What Our Students Say',
      shareExperience: 'Share Your Experience',
      name: 'Your Name *',
      course: 'Course Attended *',
      rating: 'Rating *',
      reviewLabel: 'Your Review *',
      placeholderReview: 'Share your learning experience with ADHARA SHADJA...',
      submitReview: 'Submit Review',
      submittingReview: 'Submitting Review...',
      successReview: 'Thank you for your review! It has been added.',
      loadingReviews: 'Loading reviews...'
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'Get in Touch with ADHARA SHADJA',
      phone: 'Phone',
      phoneHours: 'Available Mon-Fri, 9AM-6PM IST',
      email: 'Email',
      location: 'Location',
      locationPlace: 'Hirehadda, North Kanara',
      locationState: 'Karnataka, India',
      nameLabel: 'Name *',
      emailLabel: 'Email *',
      phoneLabel: 'Phone',
      subjectLabel: 'Subject *',
      messageLabel: 'Message *',
      placeholderName: 'Your name',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'Your phone number',
      placeholderSubject: 'Music Training Inquiry',
      placeholderMessage: 'Please let us know your requirements, background, and which category or genre (Classical, Devotional, Ghazal, Thumri) you are interested in...',
      sendBtn: 'Send Message',
      sendingBtn: 'Sending...',
      successMsg: 'Thank you for reaching out! We will contact you soon.'
    },
    footer: {
      aboutText: 'Dedicated to preserving and teaching the tradition of Indian Classical Music through structured training and personal mentorship.',
      quickLinks: 'Quick Links',
      home: 'Home',
      aboutUs: 'About Us',
      courses: 'Categories',
      contact: 'Contact',
      contactInfo: 'Contact Info',
      followUs: 'Follow Us',
      rights: 'All rights reserved.'
    }
  },
  kn: {
    langName: 'ಕನ್ನಡ',
    nav: {
      onlineClasses: 'ಆನ್‌ಲೈನ್ ತರಗತಿಗಳು',
      about: 'ನಮ್ಮ ಬಗ್ಗೆ',
      guru: 'ನಮ್ಮ ಗುರುಗಳು',
      courses: 'ವಿಭಾಗಗಳು',
      gallery: 'ಗ್ಯಾಲರಿ',
      achievements: 'ಸಾಧನೆಗಳು',
      certifications: 'ಪ್ರಮಾಣಪತ್ರಗಳು',
      community: 'ಸಮುದಾಯ',
      reviews: 'ವಿಮರ್ಶೆಗಳು',
      contact: 'ಸಂಪರ್ಕಿಸಿ',
      register: 'ನೋಂದಣಿ ಮಾಡಿ'
    },
    hero: {
      title: 'ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲ',
      subtitle: 'ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ಭವ್ಯ ಪರಂಪರೆಯ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಬೋಧನೆ',
      registerBtn: 'ಆನ್‌ಲೈನ್ ಸಂಗೀತ ತರಗತಿಗಳಿಗೆ ನೋಂದಾಯಿಸಿ',
      watchBtn: 'ಪ್ರದರ್ಶನ ವೀಕ್ಷಿಸಿ'
    },
    about: {
      title: 'ಆಧಾರ ಷಡ್ಜ ಬಗ್ಗೆ',
      subtitle: 'ಸಂಗೀತ ಪರಂಪರೆಯ ಸಂರಕ್ಷಣೆ',
      p1: 'ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲವು ಶಿಸ್ತುಬದ್ಧ ತರಬೇತಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನದ ಮೂಲಕ ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಸಂಪ್ರದಾಯವನ್ನು ಕಲಿಸಲು ಮತ್ತು ಸಂರಕ್ಷಿಸಲು ಸಮರ್ಪಿತವಾಗಿದೆ. ಉತ್ತರ ಕನ್ನಡ ಜಿಲ್ಲೆಯ ಹೀರೇಹದ್ದದ ಸುಂದರ ಗ್ರಾಮೀಣ ಪರಿಸರದಲ್ಲಿ ಸ್ಥಾಪಿತವಾಗಿರುವ ನಮ್ಮ ಸಂಸ್ಥೆಯು, ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಕಲಿಯಲು ಉತ್ಸುಕರಾಗಿರುವ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಸಾಂಪ್ರದಾಯಿಕ ಶಿಕ್ಷಣ ಒದಗಿಸುತ್ತಿದೆ.',
      p2: 'ನಾವು ಆನ್‌ಲೈನ್ ಮತ್ತು ಆಫ್‌ಲೈನ್ ತರಗತಿಗಳೆರಡನ್ನೂ ನಡೆಸುತ್ತೇವೆ. ಈ ಮೂಲಕ ದೇಶ-ವಿದೇಶಗಳ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಕಲಿಯುವ ಸದವಕಾಶ ಕಲ್ಪಿಸಿದ್ದೇವೆ. ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳು ಪ್ರತಿಭೆಯನ್ನು ಪೋಷಿಸಲು, ಅಧಿಕೃತ ಪರಂಪರೆಯನ್ನು ಉಳಿಸಲು ಮತ್ತು ಹಿಂದೂಸ್ತಾನಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ಸೌಂದರ್ಯವನ್ನು ಆಸ್ವಾದಿಸುವ ಸಮುದಾಯವನ್ನು ನಿರ್ಮಿಸಲು ರೂಪಿಸಲಾಗಿದೆ.',
      missionTitle: 'ನಮ್ಮ ಧ್ಯೇಯ',
      missionText: 'ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ಸಾರ ಮತ್ತು ಸತ್ಯತೆಯನ್ನು ಕಾಪಾಡಿಕೊಂಡು, ವ್ಯವಸ್ಥಿತ ತರಬೇತಿ, ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳ ಮೂಲಕ ಸಂಗೀತ ಪರಂಪರೆಯನ್ನು ಮುಂದಿನ ಪೀಳಿಗೆಗೆ ತಲುಪಿಸುವುದು.',
      expertTraining: 'ಪರಿಣಿತ ತರಬೇತಿ',
      expertTrainingDesc: 'ದಶಕಗಳ ಅಭ್ಯಾಸವಿರುವ ಅನುಭವಿ ಗುರುಗಳಿಂದ ನೇರ ಶಿಕ್ಷಣ',
      curriculum: 'ಕ್ರಮಬದ್ಧ ಪಠ್ಯಕ್ರಮ',
      curriculumDesc: 'ಸ್ವರಾಭ್ಯಾಸದಿಂದ ಹಿಡಿದು ರಾಗ-ವಿಸ್ತಾರದವರೆಗಿನ ಹಂತ ಹಂತದ ಕಲಿಕೆ',
      flexibility: 'ಅನುಕೂಲಕರ ಕಲಿಕೆ',
      flexibilityDesc: 'ನಿಮ್ಮ ಸಮಯಕ್ಕೆ ತಕ್ಕಂತೆ ಆನ್‌ಲೈನ್ ಮತ್ತು ಆಫ್‌ಲೈನ್ ಆಯ್ಕೆಗಳು'
    },
    guru: {
      title: 'ನಮ್ಮ ಗುರುಗಳು',
      subtitle: 'ಗುರುಕುಲ ಪರಂಪರೆಯಿಂದ ಕಲಿಯಿರಿ',
      name: 'ಶ್ರೀ ವಿನಾಯಕ ಹೆಗಡೆ ಹೀರೆಹದ್ದ',
      role: 'ಸಂಸ್ಥಾಪಕರು ಮತ್ತು ಗುರುಗಳು',
      experience: 'ಅನುಭವ',
      experienceDesc: 'ಹಲವು ದಶಕಗಳ ಕಠಿಣ ಸಾಧನೆ, ಶಿಕ್ಷಣ ಮತ್ತು ಸಂಗೀತ ಕಛೇರಿಗಳು',
      background: 'ಗುರು ಪರಂಪರೆ',
      backgroundDesc: 'ಪಂಡಿತ್ ಗಣಪತಿ ಭಟ್ ಹಾಸಣಗಿ ಅವರ ಹಿರಿಯ ಶಿಷ್ಯರು',
      expertise: 'ಪರಿಣತಿ',
      expertiseDesc: 'ಹಿಂದೂಸ್ತಾನಿ ಶಾಸ್ತ್ರೀಯ ಗಾಯನ ಸಂಗೀತ',
      aboutGuruTitle: 'ಶ್ರೀ ವಿನಾಯಕ ಹೆಗಡೆ ಅವರ ಬಗ್ಗೆ',
      aboutGuruText: 'ಶ್ರೀ ವಿನಾಯಕ ಹೆಗಡೆ ಹೀರೆಹದ್ದ ಅವರು ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ಸಂರಕ್ಷಣೆ ಮತ್ತು ಪ್ರಚಾರಕ್ಕಾಗಿ ತಮ್ಮ ಜೀವನವನ್ನು ಮುಡಿಪಾಗಿಟ್ಟಿರುವ ಪ್ರತಿಭಾವಂತ ಸಂಗೀತಗಾರರು. ಅವರು ಕರ್ನಾಟಕ ರಾಜ್ಯಾದ್ಯಂತ ನೂರಾರು ಸಂಗೀತ ಕಛೇರಿಗಳನ್ನು ನೀಡಿದ್ದಾರೆ ಮತ್ತು ತಮ್ಮ ಗುರುಗಳೊಂದಿಗೆ ಭಾರತದಾದ್ಯಂತ ಹಾಗೂ ದುಬೈ, ಅಬುಧಾಬಿಯಂತಹ ಅಂತಾರಾಷ್ಟ್ರೀಯ ವೇದಿಕೆಗಳಲ್ಲಿ ಗಾಯನ ಪ್ರಸ್ತುತಪಡಿಸಿದ್ದಾರೆ.',
      philosophyTitle: 'ಬೋಧನಾ ತತ್ವ',
      philosophyText: '"ಸಂಗೀತವು ಕೇವಲ ಒಂದು ಕಲೆಯಲ್ಲ; ಅದೊಂದು ಜೀವನ ವಿಧಾನ. ಜೀವಂತ ಗುರುಗಳಿಂದ ನಿಷ್ಠಾವಂತ ಅಭ್ಯಾಸ ಮತ್ತು ಸತ್ಯವಾದ ಕಲಿಕೆಯ ಮೂಲಕ, ಒಬ್ಬರು ಈ ಪವಿತ್ರ ಸಂಪ್ರದಾಯದ ಸೂಕ್ಷ್ಮತೆಗಳನ್ನು ಕರಗತ ಮಾಡಿಕೊಳ್ಳಬಹುದು ಮತ್ತು ಮುಂದಿನ ಪೀಳಿಗೆಗೆ ಅದನ್ನು ಸಂರಕ್ಷಿಸಬಹುದು."'
    },
    courses: {
      title: 'ಕಲಿಕಾ ವಿಭಾಗಗಳು',
      subtitle: 'ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಗಾಯನ ತರಬೇತಿ',
      loading: 'ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
      contactFees: 'ಶುಲ್ಕ ಮತ್ತು ಬ್ಯಾಚ್ ಸಮಯದ ವಿವರಗಳಿಗಾಗಿ ಸಂಪರ್ಕಿಸಿ',
      enrollBtn: 'ನೋಂದಣಿ ಮಾಡಿ',
      juniorTitle: 'ಜೂನಿಯರ್ ವರ್ಗ',
      juniorLevel: 'ಆರಂಭಿಕ ಹಂತ (Junior)',
      seniorTitle: 'ಸೀನಿಯರ್ ವರ್ಗ',
      seniorLevel: 'ಮಧ್ಯಮ ಹಂತ (Senior)',
      vidwathTitle: 'ವಿದ್ವತ್ ವರ್ಗ',
      vidwathLevel: 'ಉನ್ನತ ಹಂತ (Vidwath)',
      specialGenresTitle: 'ವಿಶೇಷ ಸಂಗೀತ ಪ್ರಕಾರಗಳ ಬೋಧನೆ',
      specialGenresSubtitle: 'ನಾವು ಶಾಸ್ತ್ರೀಯ ಭಕ್ತಿ ಸಂಗೀತ, ಗಜಲ್ ಮತ್ತು ಠುಮ್ರಿ ಪ್ರಕಾರಗಳಲ್ಲೂ ಬೋಧನೆ ನೀಡುತ್ತೇವೆ',
      genreDevotional: 'ಶಾಸ್ತ್ರೀಯ ಭಕ್ತಿ ಸಂಗೀತ',
      genreDevotionalDesc: 'ದಾಸರ ಪದಗಳು, ವಚನಗಳು, ಭಜನೆಗಳು, ಅಭಂಗ್ ಮತ್ತು ಸ್ತೋತ್ರಗಳ ಶುದ್ಧ ಶಾಸ್ತ್ರೀಯ ರಾಗಾಧಾರಿತ ಗಾಯನ',
      genreGhazals: 'ಗಜಲ್ ಗಾಯನ',
      genreGhazalsDesc: 'ಉರ್ದು ಮತ್ತು ಹಿಂದಿ ಕಾವ್ಯಗಳ ಭಾವಪೂರ್ಣ ಗಜಲ್ ಪ್ರಸ್ತುತಿ ಹಾಗೂ ಗಾಯನ ಸೂಕ್ಷ್ಮತೆಗಳು',
      genreThumri: 'ಠುಮ್ರಿ ಮತ್ತು ದಾದ್ರಾ',
      genreThumriDesc: 'ಉಪ-ಶಾಸ್ತ್ರೀಯ ಶೈಲಿಯ ಬೋಲ್-ಬನಾವ್, ಭಾವ ಪ್ರಧಾನ ಠುಮ್ರಿ ಮತ್ತು ದಾದ್ರಾ ಬಂದಿಶ್‌ಗಳು'
    },
    facilities: {
      title: 'FACILITIES FOR STUDENTS',
      examPrepTitle: 'EXAM PREPARATION',
      examPrepDesc: 'ವಿದ್ಯಾರ್ಥಿಗಳು ಕೆಎಸ್‌ಇಇ ಬೋರ್ಡ್ ಬೆಂಗಳೂರು ಮತ್ತು ಎಬಿಜಿಎಂ ಸಂಗೀತ ಪರೀಕ್ಷೆಗಳಿಗೆ ಹಾಜರಾಗಬಹುದು',
      scholarshipTitle: 'SCHOLARSHIP SUPPORT',
      scholarshipDesc: 'ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳು ರಾಜ್ಯ, ಕೇಂದ್ರ ಸರ್ಕಾರ ಮತ್ತು ಎನ್‌ಜಿಒಗಳಿಂದ ವಿದ್ಯಾರ್ಥಿವೇತನಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಬಹುದು'
    },
    achievements: {
      title: 'ನಮ್ಮ ಸಾಧನೆಗಳು',
      subtitle: 'ಮೈಲಿಗಲ್ಲುಗಳು ಮತ್ತು ಗೌರವಗಳು',
      studentsTrained: 'ತರಬೇತಿ ಪಡೆದ ವಿದ್ಯಾರ್ಥಿಗಳು',
      studentsTrainedDesc: '500ಕ್ಕೂ ಹೆಚ್ಚು ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಯಶಸ್ವಿ ಮಾರ್ಗದರ್ಶನ',
      performances: 'ಸಂಗೀತ ಕಛೇರಿಗಳು',
      performancesDesc: 'ದೇಶ ಮತ್ತು ವಿದೇಶಗಳಲ್ಲಿ 100ಕ್ಕೂ ಹೆಚ್ಚು ಪ್ರತಿಷ್ಠಿತ ವೇದಿಕೆ ಪ್ರದರ್ಶನಗಳು',
      awards: 'ಪ್ರಶಸ್ತಿ ಮತ್ತು ಪುರಸ್ಕಾರಗಳು',
      awardsDesc: 'ಹಲವಾರು ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಸಂಗೀತ ಸಂಸ್ಥೆಗಳಿಂದ ಸನ್ಮಾನ',
      experienceYears: 'ವರ್ಷಗಳ ಪರಂಪರೆ',
      experienceYearsDesc: 'ದಶಕಗಳ ಕಾಲ ನಿರಂತರ ಗುರು-ಶಿಷ್ಯ ಸಂಪ್ರದಾಯದ ಸೇವೆ',
      highlightsTitle: 'ಪ್ರಮುಖ ಮುಖ್ಯಾಂಶಗಳು',
      h1: '✓ ಪ್ರತಿಷ್ಠಿತ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಗುರು-ಶಿಷ್ಯ ಪರಂಪರೆ',
      h2: '✓ ಹಿಂದೂಸ್ತಾನಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದಲ್ಲಿ ನೂರಾರು ಶಿಷ್ಯರ ಸಿದ್ಧತೆ',
      h3: '✓ ಕರ್ನಾಟಕ ಮತ್ತು ಇತರೆಡೆ ನಿರಂತರ ಸಂಗೀತ ಕಾರ್ಯಕ್ರಮಗಳ ಆಯೋಜನೆ',
      h4: '✓ ರಾಷ್ಟ್ರೀಯ ಮತ್ತು ಅಂತರರಾಷ್ಟ್ರೀಯ ವೇದಿಕೆಗಳಲ್ಲಿ ಮಿಂಚುತ್ತಿರುವ ವಿದ್ಯಾರ್ಥಿಗಳು'
    },
    certifications: {
      title: 'ಸಂಗೀತ ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ಪರೀಕ್ಷೆಗಳು',
      subtitle: 'ಗಾಂಧರ್ವ ಮಹಾವಿದ್ಯಾಲಯ ಪರೀಕ್ಷಾ ಸಿದ್ಧತೆ ಮತ್ತು ಆಧಾರ ಷಡ್ಜ ಟ್ರಸ್ಟ್ ಪ್ರಮಾಣಪತ್ರಗಳು',
      intro: 'ನಾವು ಅಖಿಲ ಭಾರತೀಯ ಗಾಂಧರ್ವ ಮಹಾವಿದ್ಯಾಲಯದ ಪಠ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಕ್ರಮಬದ್ಧ ತರಬೇತಿ ನೀಡುತ್ತೇವೆ. ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ವಿವಿಧ ಮಂಡಳಿಯ ಸಂಗೀತ ಪರೀಕ್ಷೆಗಳಿಗೆ ಸಿದ್ಧಪಡಿಸುತ್ತೇವೆ ಮತ್ತು ನಮ್ಮ ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲ ಟ್ರಸ್ಟ್‌ನಿಂದ ಅಧಿಕೃತ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ನೀಡಲಾಗುತ್ತದೆ.',
      benefitsTitle: 'ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಪ್ರಮಾಣಪತ್ರದ ಪ್ರಯೋಜನಗಳು',
      b1: '✓ ಗಾಂಧರ್ವ ಮಹಾವಿದ್ಯಾಲಯ ಪಠ್ಯಕ್ರಮದ ಪ್ರಕಾರ ಕ್ರಮಬದ್ಧ ಬೋಧನೆ',
      b2: '✓ ಜೂನಿಯರ್, ಸೀನಿಯರ್ ಮತ್ತು ವಿದ್ವತ್ ಪರೀಕ್ಷೆಗಳಿಗೆ ಸಮಗ್ರ ತರಬೇತಿ',
      b3: '✓ ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲ ಟ್ರಸ್ಟ್‌ನಿಂದ ಅಧಿಕೃತ ಪ್ರಮಾಣಪತ್ರಗಳು',
      b4: '✓ ವೇದಿಕೆ ಕಛೇರಿಗಳು ಮತ್ತು ಬೋಧನೆಗೆ ಸೂಕ್ತ ಮಾರ್ಗದರ್ಶನ',
      c1_title: 'ಜೂನಿಯರ್ ಹಂತದ ಪ್ರಮಾಣಪತ್ರ (Junior Category)',
      c1_desc: 'ಗಾಂಧರ್ವ ಪಠ್ಯಕ್ರಮದ ಅಡಿಯಲ್ಲಿ ಪ್ರಾಥಮಿಕ ರಾಗಗಳು, ಸ್ವರಾಭ್ಯಾಸ ಮತ್ತು ತಾಳಗಳ ಆರಂಭಿಕ ಕಲಿಕೆಯ ಪ್ರಮಾಣಪತ್ರ',
      c2_title: 'ಸೀನಿಯರ್ ಹಂತದ ಪ್ರಮಾಣಪತ್ರ (Senior Category)',
      c2_desc: 'ರಾಗ ವಿಸ್ತಾರ, ಬಂದಿಶ್‌ಗಳು, ಛೋಟಾ ಖಯಾಲ್ ಮತ್ತು ಸೀನಿಯರ್ ಪರೀಕ್ಷೆಯ ತೇರ್ಗಡೆ ದೃಢೀಕರಣ',
      c3_title: 'ವಿದ್ವತ್ ಹಂತದ ಪ್ರಮಾಣಪತ್ರ (Vidwath Category)',
      c3_desc: 'ಸಂಕೀರ್ಣ ರಾಗಗಳು, ಬಡಾ ಖಯಾಲ್, ತರಾನಾ ಮತ್ತು ಕಛೇರಿ ಪ್ರಸ್ತುತಿಯ ಉನ್ನತ ಮಟ್ಟದ ಪಾಂಡಿತ್ಯದ ಪ್ರಮಾಣಪತ್ರ',
      c4_title: 'ಆಧಾರ ಷಡ್ಜ ಟ್ರಸ್ಟ್ ಬೋಧನಾ ಮತ್ತು ಗೌರವ ಪ್ರಮಾಣಪತ್ರ',
      c4_desc: 'ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತವನ್ನು ಇತರರಿಗೆ ಬೋಧಿಸುವ ಮತ್ತು ಪ್ರಚಾರ ಮಾಡುವ ಅರ್ಹತೆ ಹೊಂದಿರುವ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಟ್ರಸ್ಟ್ ಗೌರವ'
    },
    gallery: {
      title: 'ಗ್ಯಾಲರಿ ಮತ್ತು ಮಾಧ್ಯಮ',
      subtitle: 'ಸಾಕ್ಷ್ಯಚಿತ್ರಗಳು, ಗಾಯನ ಪ್ರಸ್ತುತಿ, ಮಾಸಿಕ ಬೈಠಕ್ ಮತ್ತು ಗುರುವಂದನಾ',
      viewFullBtn: 'ಪೂರ್ಣ ಗ್ಯಾಲರಿ ವೀಕ್ಷಿಸಿ →',
      exploreHeading: 'ಗುರುಕುಲದ ಅಪರೂಪದ ಕ್ಷಣಗಳು',
      documentaryTitle: 'ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲದ ಸಾಕ್ಷ್ಯಚಿತ್ರ (ಡಾಕ್ಯುಮೆಂಟರಿ)',
      documentaryDesc: 'ಹೀರೆಹದ್ದದಲ್ಲಿರುವ ನಮ್ಮ ಗುರುಕುಲದ ಪರಂಪರೆ ಮತ್ತು ಸಂಗೀತ ಪಯಣದ ನೋಟ',
      studentPerfTitle: 'ವಿದ್ಯಾರ್ಥಿಯ ಶಾಸ್ತ್ರೀಯ ಗಾಯನ ಪ್ರಸ್ತುತಿ',
      studentPerfDesc: 'ರಾಗಾಲಾಪನೆ ಮತ್ತು ಗಾಯನ ಪ್ರತಿಭೆಯನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತಿರುವ ಗುರುಕುಲದ ಶಿಷ್ಯ',
      teachingSessionTitle: 'ಗುರುಕುಲ ಸಂಗೀತ ಪಾಠ / ಬೋಧನಾ ಅಧಿವೇಶನ',
      teachingSessionDesc: 'ಸಾಂಪ್ರದಾಯಿಕ ಗುರು-ಶಿಷ್ಯ ಪರಂಪರೆಯ ನೇರ ಸಂಗೀತ ಬೋಧನೆಯ ಕ್ಷಣಗಳು',
      guruPerfTitle: 'ಶ್ರೀ ವಿನಾಯಕ ಹೆಗಡೆ ಅವರ ಶಾಸ್ತ್ರೀಯ ಗಾಯನ',
      guruPerfDesc: 'ಹಿಂದೂಸ್ತಾನಿ ರಾಗಾಲಾಪನೆಯಲ್ಲಿ ಗುರುಗಳ ದಿವ್ಯ ಗಾಯನ ಪ್ರಸ್ತುತಿ',
      baithakTitle: 'ಮಾಸಿಕ ಬೈಠಕ್ - ಸಂಗೀತ ಸಮ್ಮಿಲನ',
      baithakDesc: 'ಗುರುಕುಲದಲ್ಲಿ ಪ್ರತಿ ತಿಂಗಳು ನಡೆಯುವ ಶಾಸ್ತ್ರೀಯ ಗಾಯನ ಮತ್ತು ರಿಯಾಜ್ ಬೈಠಕ್',
      guruvandanaTitle: 'ಗುರುವಂದನಾ ಉತ್ಸವ ಮತ್ತು ಸನ್ಮಾನ ಕಾರ್ಯಕ್ರಮ',
      guruvandanaDesc: 'ಗುರು ಪರಂಪರೆಗೆ ಗೌರವ ನಮನ ಮತ್ತು ಸನ್ಮಾನದ ಪವಿತ್ರ ಮಹೋತ್ಸವ',
      studentConcertTitle: 'ವಿದ್ಯಾರ್ಥಿಗಳ ಸಂಗೀತ ಕಛೇರಿ',
      traditionalPerfTitle: 'ಸಾಂಪ್ರದಾಯಿಕ ಗುರುಕುಲ ಕಾರ್ಯಕ್ರಮ',
      uploadBtn: '+ ಫೋಟೋ / ವಿಡಿಯೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      filterAll: 'ಎಲ್ಲಾ ಮಾಧ್ಯಮಗಳು',
      filterDocumentary: 'ಸಾಕ್ಷ್ಯಚಿತ್ರಗಳು',
      filterPerformances: 'ಗಾಯನ ಪ್ರಸ್ತುತಿ',
      filterTeaching: 'ಪಾಠ / ಬೋಧನೆ',
      filterBaithak: 'ಮಾಸಿಕ ಬೈಠಕ್',
      filterGuruvandana: 'ಗುರುವಂದನಾ ಕಾರ್ಯಕ್ರಮ',
      filterUploaded: 'ಅಡ್ಮಿನ್ ಅಪ್‌ಲೋಡ್‌ಗಳು',
      uploadModalTitle: 'ಗ್ಯಾಲರಿಗೆ ಹೊಸ ಮಾಧ್ಯಮ ಸೇರಿಸಿ (ಅಧಿಕೃತ ಪ್ರವೇಶ)',
      mediaType: 'ಮಾಧ್ಯಮ ಪ್ರಕಾರ',
      typePhoto: 'ಫೋಟೋ (ಚಿತ್ರ ಅಪ್‌ಲೋಡ್)',
      typeVideo: 'ಯೂಟ್ಯೂಬ್ ವಿಡಿಯೋ',
      mediaTitle: 'ಶೀರ್ಷಿಕೆ *',
      mediaCategory: 'ವರ್ಗ *',
      mediaDescription: 'ವಿವರಣೆ',
      mediaYoutubeUrl: 'ಯೂಟ್ಯೂಬ್ ಲಿಂಕ್ (ಉದಾ: https://youtu.be/...)',
      mediaFile: 'ಚಿತ್ರದ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ',
      submitUpload: 'ಗ್ಯಾಲರಿಗೆ ಸೇರಿಸಿ',
      cancel: 'ರದ್ದುಗೊಳಿಸಿ',
      backToHome: '← ಮುಖ್ಯ ಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
      noItems: 'ಈ ವರ್ಗದಲ್ಲಿ ಯಾವುದೇ ಮಾಧ್ಯಮ ಕಂಡುಬಂದಿಲ್ಲ.',
      successUpload: 'ಮಾಧ್ಯಮವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಗ್ಯಾಲರಿಗೆ ಸೇರಿಸಲಾಗಿದೆ!',
      authRequiredTitle: 'ಅಧಿಕೃತ ನಿರ್ವಾಹಕರಿಗೆ ಮಾತ್ರ ಪ್ರವೇಶ',
      authRequiredDesc: 'ಕೇವಲ ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲದ ಅಧಿಕೃತ ನಿರ್ವಾಹಕರು ಮತ್ತು ಗುರುಗಳು ಮಾತ್ರ ಮಾಧ್ಯಮವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಬಹುದು.',
      enterPasscode: 'ನಿರ್ವಾಹಕ ಪಾಸ್‌ಕೋಡ್ ನಮೂದಿಸಿ',
      passcodePlaceholder: 'ರಹಸ್ಯ ಸಂಕೇತ (Default: adhara@2024)',
      verifyLoginBtn: 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
      invalidPasscode: 'ತಪ್ಪಾದ ಪಾಸ್‌ಕೋಡ್! ದಯವಿಟ್ಟು ಸರಿಯಾದ ಅಧಿಕೃತ ಕೀಲಿಯನ್ನು ನಮೂದಿಸಿ.',
      adminLoggedInBadge: 'ಅಧಿಕೃತ ನಿರ್ವಾಹಕರು ಸಕ್ರಿಯ',
      logoutBtn: 'ಲಾಗ್ ಔಟ್',
      adminPasscodeHint: 'ಅನಧಿಕೃತ ಅಪ್‌ಲೋಡ್‌ಗಳನ್ನು ತಡೆಯಲು ಪಾಸ್‌ಕೋಡ್ ಅಗತ್ಯವಿದೆ.'
    },
    registration: {
      title: 'ವಿದ್ಯಾರ್ಥಿ ನೋಂದಣಿ',
      subtitle: 'ನಮ್ಮೊಂದಿಗೆ ನಿಮ್ಮ ಸಂಗೀತ ಪಯಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
      firstName: 'ಮೊದಲ ಹೆಸರು *',
      lastName: 'ಕೊನೆಯ ಹೆಸರು *',
      email: 'ಇಮೇಲ್ ವಿಳಾಸ *',
      phone: 'ದೂರವಾಣಿ ಸಂಖ್ಯೆ *',
      age: 'ವಯಸ್ಸು *',
      experience: 'ಹಿಂದಿನ ಸಂಗೀತ ಅನುಭವ / ವರ್ಗ',
      expBeginner: 'ಜೂನಿಯರ್ ವರ್ಗ (Junior - ಹೊಸದಾಗಿ ಕಲಿಯುವವರು)',
      expIntermediate: 'ಸೀನಿಯರ್ ವರ್ಗ (Senior - 1-2 ವರ್ಷಗಳ ಅನುಭವ)',
      expAdvanced: 'ವಿದ್ವತ್ ವರ್ಗ (Vidwath - 3+ ವರ್ಷಗಳ ಅನುಭವ)',
      selectCourse: 'ಕೋರ್ಸ್ / ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ *',
      address: 'ವಿಳಾಸ *',
      city: 'ಊರು/ನಗರ *',
      state: 'ರಾಜ್ಯ *',
      country: 'ದೇಶ *',
      submitBtn: 'ನೋಂದಣಿ ಸಲ್ಲಿಸಿ',
      submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
      successMsg: 'ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ! ತರಗತಿಯ ಸಮಯ ಮತ್ತು ವಿವರಗಳೊಂದಿಗೆ ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
      placeholderName: 'ನಿಮ್ಮ ಮೊದಲ ಹೆಸರು',
      placeholderLastName: 'ನಿಮ್ಮ ಕೊನೆಯ ಹೆಸರು',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      placeholderAge: 'ನಿಮ್ಮ ವಯಸ್ಸು',
      placeholderAddress: 'ವಿಳಾಸ',
      placeholderCity: 'ಊರು/ನಗರ'
    },
    community: {
      title: 'ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
      subtitle: 'ಸಂಗೀತ ಪ್ರೇಮಿಗಳು ಮತ್ತು ಕಲಿಯುವವರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
      intro: 'ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ವಿದ್ಯಾರ್ಥಿಗಳು, ರಸಿಕರು ಮತ್ತು ಸಾಧಕರ ಉತ್ಸಾಹಭರಿತ ಸಮುದಾಯದ ಭಾಗವಾಗಿರಿ. ನಿಮ್ಮ ಸಂಗೀತಾಸಕ್ತಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಮತ್ತು ಒಟ್ಟಿಗೆ ಬೆಳೆಯಿರಿ.',
      forums: 'ಆನ್‌ಲೈನ್ ಚರ್ಚಾವೇದಿಕೆ',
      forumsDesc: 'ಸಂಗೀತದ ಪರಿಕಲ್ಪನೆಗಳನ್ನು ಚರ್ಚಿಸಿ ಮತ್ತು ಸಹ ಕಲಿಯುವವರಿಂದ ಉಪಯುಕ್ತ ಸಲಹೆ ಪಡೆಯಿರಿ',
      events: 'ನಿರಂತರ ಕಾರ್ಯಕ್ರಮಗಳು',
      eventsDesc: 'ಪ್ರಸಿದ್ಧ ಸಂಗೀತಗಾರರಿಂದ ಆನ್‌ಲೈನ್ ಕಛೇರಿಗಳು, ಕಾರ್ಯಾಗಾರಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶನ',
      networking: 'ಸಂಪರ್ಕ ಜಾಲ',
      networkingDesc: 'ಸಂಗೀತ ಕ್ಷೇತ್ರದ ಪರಿಣಿತರು ಮತ್ತು ಕಲಾವಿದರೊಂದಿಗೆ ಸಂಪರ್ಕ ಬೆಳೆಸಿ',
      resources: 'ಸಂಪನ್ಮೂಲ ಹಂಚಿಕೆ',
      resourcesDesc: 'ಅತ್ಯುತ್ತಮ ಸಂಗೀತ ಟಿಪ್ಪಣಿಗಳು ಮತ್ತು ಅಪರೂಪದ ರೆಕಾರ್ಡಿಂಗ್‌ಗಳ ಸೌಲಭ್ಯ',
      followUs: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮಗಳಲ್ಲಿ ನಮ್ಮನ್ನು ಫಾಲೋ ಮಾಡಿ',
      supportMission: 'ನಮ್ಮ ಧ್ಯೇಯವನ್ನು ಬೆಂಬಲಿಸಿ',
      supportDesc: 'ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಪರಂಪರೆಯನ್ನು ಉಳಿಸಲು ಮತ್ತು ಬೆಳೆಸಲು ನಮಗೆ ಕೈಜೋಡಿಸಿ',
      contributeBtn: 'ಈಗಲೇ ದೇಣಿಗೆ ನೀಡಿ',
      processing: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...'
    },
    reviews: {
      title: 'ವಿದ್ಯಾರ್ಥಿಗಳ ವಿಮರ್ಶೆಗಳು',
      subtitle: 'ನಮ್ಮ ವಿದ್ಯಾರ್ಥಿಗಳು ಏನು ಹೇಳುತ್ತಾರೆ',
      shareExperience: 'ನಿಮ್ಮ ಅನಿಸಿಕೆ ಹಂಚಿಕೊಳ್ಳಿ',
      name: 'ನಿಮ್ಮ ಹೆಸರು *',
      course: 'ಭಾಗವಹಿಸಿದ ಕೋರ್ಸ್ *',
      rating: 'ರೇಟಿಂಗ್ *',
      reviewLabel: 'ನಿಮ್ಮ ವಿಮರ್ಶೆ *',
      placeholderReview: 'ಆಧಾರ ಷಡ್ಜದಲ್ಲಿ ನಿಮ್ಮ ಕಲಿಕೆಯ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...',
      submitReview: 'ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ',
      submittingReview: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
      successReview: 'ನಿಮ್ಮ ವಿಮರ್ಶೆಗೆ ಧನ್ಯವಾದಗಳು! ಅದನ್ನು ಸೇರಿಸಲಾಗಿದೆ.',
      loadingReviews: 'ವಿಮರ್ಶೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...'
    },
    contact: {
      title: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      subtitle: 'ಆಧಾರ ಷಡ್ಜ ಗುರುಕುಲದೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
      phone: 'ದೂರವಾಣಿ',
      phoneHours: 'ಸೋಮ-ಶುಕ್ರ, ಬೆಳಗ್ಗೆ 9 ರಿಂದ ಸಂಜೆ 6 IST',
      email: 'ಇಮೇಲ್',
      location: 'ಸ್ಥಳ',
      locationPlace: 'ಹೀರೆಹದ್ದ, ಉತ್ತರ ಕನ್ನಡ',
      locationState: 'ಕರ್ನಾಟಕ, ಭಾರತ',
      nameLabel: 'ಹೆಸರು *',
      emailLabel: 'ಇಮೇಲ್ *',
      phoneLabel: 'ದೂರವಾಣಿ',
      subjectLabel: 'ವಿಷಯ *',
      messageLabel: 'ಸಂದೇಶ *',
      placeholderName: 'ನಿಮ್ಮ ಹೆಸರು',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      placeholderSubject: 'ಸಂಗೀತ ತರಬೇತಿ ವಿಚಾರಣೆ',
      placeholderMessage: 'ನಿಮ್ಮ ಸಂಗೀತ ಆಸಕ್ತಿ ಮತ್ತು ಯಾವ ಪ್ರಕಾರ (ಶಾಸ್ತ್ರೀಯ, ಭಕ್ತಿ ಸಂಗೀತ, ಗಜಲ್, ಠುಮ್ರಿ) ಕಲಿಯಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ತಿಳಿಸಿ...',
      sendBtn: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      sendingBtn: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
      successMsg: 'ಸಂಪರ್ಕಿಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು! ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.'
    },
    footer: {
      aboutText: 'ಶಿಸ್ತುಬದ್ಧ ತರಬೇತಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನದ ಮೂಲಕ ಭಾರತೀಯ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತದ ಪರಂಪರೆಯನ್ನು ಸಂರಕ್ಷಿಸಲು ಮತ್ತು ಕಲಿಸಲು ಸಮರ್ಪಿತವಾಗಿದೆ.',
      quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
      home: 'ಮುಖಪುಟ',
      aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
      courses: 'ವಿಭಾಗಗಳು',
      contact: 'ಸಂಪರ್ಕಿಸಿ',
      contactInfo: 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
      followUs: 'ನಮ್ಮನ್ನು ಫಾಲೋ ಮಾಡಿ',
      rights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.'
    }
  },
  hi: {
    langName: 'हिन्दी',
    nav: {
      onlineClasses: 'ऑनलाइन कक्षाएं',
      about: 'हमारे बारे में',
      guru: 'हमारे गुरु',
      courses: 'श्रेणियां',
      gallery: 'गैलरी',
      achievements: 'उपलब्धियां',
      certifications: 'प्रमाणपत्र',
      community: 'समुदाय',
      reviews: 'समीक्षाएं',
      contact: 'संपर्क करें',
      register: 'पंजीकरण करें'
    },
    hero: {
      title: 'आधार षड्ज गुरुकुल',
      subtitle: 'भारतीय शास्त्रीय संगीत की समृद्ध परंपरा का संरक्षण एवं शिक्षण',
      registerBtn: 'ऑनलाइन संगीत कक्षाओं के लिए पंजीकरण करें',
      watchBtn: 'प्रस्तुति देखें'
    },
    about: {
      title: 'आधार षड्ज के बारे में',
      subtitle: 'संगीत धरोहर का संरक्षण',
      p1: 'आधार षड्ज गुरुकुल संरचित प्रशिक्षण और व्यक्तिगत मार्गदर्शन के माध्यम से भारतीय शास्त्रीय संगीत परंपराओं को सिखाने और संरक्षित करने के लिए समर्पित है। उत्तर कन्नड़, कर्नाटक के सुरम्य ग्रामीण क्षेत्र हिरेहड्डा में स्थापित, हमारा संस्थान शास्त्रीय संगीत सीखने के इच्छुक छात्रों को प्रामाणिक ज्ञान प्रदान करता है।',
      p2: 'हम ऑनलाइन और ऑफलाइन दोनों प्रकार की कक्षाएं संचालित करते हैं, जिससे देश-विदेश के शिक्षार्थियों को शास्त्रीय संगीत सीखने का अवसर मिलता है। हमारे कार्यक्रम प्रतिभा को निखारने, प्रामाणिक परंपरा को बनाए रखने और हिंदुस्तानी शास्त्रीय संगीत के सौंदर्य को संजोने के लिए तैयार किए गए हैं।',
      missionTitle: 'हमारा उद्देश्य',
      missionText: 'भारतीय शास्त्रीय संगीत की प्रामाणिकता और आत्मा को बनाए रखते हुए, सुव्यवस्थित प्रशिक्षण, मार्गदर्शन और सांस्कृतिक जुड़ाव के माध्यम से इस प्राचीन कला को भावी पीढ़ियों तक पहुँचाना।',
      expertTraining: 'विशेषज्ञ प्रशिक्षण',
      expertTrainingDesc: 'दशकों के अनुभव वाले प्रख्यात गुरुओं से प्रत्यक्ष सीखें',
      curriculum: 'व्यवस्थित पाठ्यक्रम',
      curriculumDesc: 'बुनियादी स्वरों से लेकर जटिल रागों तक चरणबद्ध शिक्षा',
      flexibility: 'लचीला शिक्षण',
      flexibilityDesc: 'आपकी सुविधा अनुसार ऑनलाइन और ऑफलाइन विकल्प'
    },
    guru: {
      title: 'हमारे गुरु',
      subtitle: 'संगीत साधक से सीखें',
      name: 'श्री विनायक हेगड़े हिरेहड्डा',
      role: 'संस्थापक एवं गुरु',
      experience: 'अनुभव',
      experienceDesc: 'दशकों की कठोर साधना, शिक्षण और संगीत प्रस्तुतियां',
      background: 'गुरु परंपरा',
      backgroundDesc: 'पं. गणपति भट हासनगी के वरिष्ठ शिष्य',
      expertise: 'विशेषज्ञता',
      expertiseDesc: 'हिंदुस्तानी शास्त्रीय गायन संगीत',
      aboutGuruTitle: 'श्री विनायक हेगड़े के बारे में',
      aboutGuruText: 'श्री विनायक हेगड़े हिरेहड्डा एक बहुमुखी संगीतकार हैं जिन्होंने अपना जीवन भारतीय शास्त्रीय संगीत के संरक्षण और शिक्षण के लिए समर्पित किया है। उन्होंने कर्नाटक सहित पूरे भारत में कई प्रस्तुतियां दी हैं और अपने गुरु के साथ दुबई, अबू धाबी जैसे अंतरराष्ट्रीय मंचों पर भी संगीत प्रस्तुत किया है।',
      philosophyTitle: 'शिक्षण दर्शन',
      philosophyText: '"संगीत केवल एक कला नहीं है; यह जीवन जीने का एक मार्ग है। एक जीवित गुरु से समर्पित अभ्यास और प्रामाणिक शिक्षा के माध्यम से, कोई भी इस पवित्र परंपरा की बारीकियों में निपुण हो सकता है और आने वाली पीढ़ियों के लिए इसे संरक्षित कर सकता है।"'
    },
    courses: {
      title: 'अध्ययन श्रेणियां',
      subtitle: 'भारतीय शास्त्रीय गायन प्रशिक्षण',
      loading: 'लोड हो रहा है...',
      contactFees: 'शुल्क एवं बैच समय के लिए संपर्क करें',
      enrollBtn: 'पंजीकरण करें',
      juniorTitle: 'जूनियर श्रेणी',
      juniorLevel: 'प्रारंभिक स्तर (Junior)',
      seniorTitle: 'सीनियर श्रेणी',
      seniorLevel: 'मध्यम स्तर (Senior)',
      vidwathTitle: 'विद्वत श्रेणी',
      vidwathLevel: 'उन्नत स्तर (Vidwath)',
      specialGenresTitle: 'विशेष संगीत विधाएं',
      specialGenresSubtitle: 'हम भक्ति शास्त्रीय संगीत, ग़ज़ल एवं ठुमरी का भी प्रामाणिक शिक्षण देते हैं',
      genreDevotional: 'भक्ति शास्त्रीय संगीत',
      genreDevotionalDesc: 'भजन, दासरपद, वचन, अभंग एवं स्तोत्रों का राग-आधारित शुद्ध शास्त्रीय गायन',
      genreGhazals: 'ग़ज़ल गायन',
      genreGhazalsDesc: 'उर्दू एवं हिंदी काव्य की भावपूर्ण ग़ज़ल प्रस्तुति, सुर-ताल एवं शब्द-अदायगी की बारीकियां',
      genreThumri: 'ठुमरी एवं दादरा',
      genreThumriDesc: 'अर्ध-शास्त्रीय उप-अंग, बोल-बनाव एवं भावप्रधान ठुमरी-दादरा बंदिशों का प्रशिक्षण'
    },
    facilities: {
      title: 'FACILITIES FOR STUDENTS',
      examPrepTitle: 'EXAM PREPARATION',
      examPrepDesc: 'छात्र केएसईई बोर्ड बैंगलोर और एबीजीएम संगीत परीक्षाओं में उपस्थित हो सकते हैं',
      scholarshipTitle: 'SCHOLARSHIP SUPPORT',
      scholarshipDesc: 'पात्र छात्र राज्य, केंद्र और गैर सरकारी संगठनों से छात्रवृत्ति के लिए आवेदन कर सकते हैं'
    },
    achievements: {
      title: 'हमारी उपलब्धियां',
      subtitle: 'उपलब्धियां और सम्मान',
      studentsTrained: 'प्रशिक्षित छात्र',
      studentsTrainedDesc: '500+ से अधिक छात्रों को शास्त्रीय गायन में प्रशिक्षित किया गया',
      performances: 'संगीत प्रस्तुतियां',
      performancesDesc: 'देश और विदेश में 100+ से अधिक प्रतिष्ठित मंच प्रस्तुतियां',
      awards: 'पुरस्कार एवं सम्मान',
      awardsDesc: 'अनेक सांस्कृतिक और शास्त्रीय संगीत संस्थानों द्वारा सम्मानित',
      experienceYears: 'वर्षों की परंपरा',
      experienceYearsDesc: 'दशकों से निरंतर गुरु-शिष्य परंपरा का निर्वहन',
      highlightsTitle: 'मुख्य विशेषताएं',
      h1: '✓ प्रतिष्ठित शास्त्रीय संगीत गुरु-शिष्य परंपरा',
      h2: '✓ हिंदुस्तानी शास्त्रीय संगीत में अनेक विद्यार्थियों को तैयार किया',
      h3: '✓ कर्नाटक और अन्य स्थानों पर नियमित संगीत कार्यक्रमों का आयोजन',
      h4: '✓ राष्ट्रीय और अंतरराष्ट्रीय मंचों पर प्रदर्शन कर रहे पूर्व छात्र'
    },
    certifications: {
      title: 'संगीत प्रमाणपत्र एवं बोर्ड परीक्षाएं',
      subtitle: 'गांधर्व महाविद्यालय परीक्षा तैयारी एवं आधार षड्ज ट्रस्ट प्रमाणपत्र',
      intro: 'हम अखिल भारतीय गांधर्व महाविद्यालय के पाठ्यक्रम के अनुसार व्यवस्थित प्रशिक्षण प्रदान करते हैं। हम छात्रों को विभिन्न प्रतिष्ठित संगीत बोर्ड परीक्षाओं के लिए तैयार करते हैं और अपने आधार षड्ज गुरुकुल ट्रस्ट से प्रामाणिक प्रमाणपत्र प्रदान करते हैं।',
      benefitsTitle: 'शैक्षणिक एवं प्रमाणपत्र के प्रमुख लाभ',
      b1: '✓ अखिल भारतीय गांधर्व महाविद्यालय पाठ्यक्रम के अनुसार अध्यापन',
      b2: '✓ जूनियर, सीनियर और विद्वत परीक्षाओं के लिए गहन तैयारी',
      b3: '✓ आधार षड्ज गुरुकुल ट्रस्ट द्वारा अधिकृत संस्थागत प्रमाणपत्र',
      b4: '✓ मंच प्रदर्शन, शास्त्रीय कॉन्सर्ट एवं संगीत शिक्षण के अवसर',
      c1_title: 'जूनियर श्रेणी प्रमाणपत्र (Junior Category)',
      c1_desc: 'गांधर्व पाठ्यक्रम के अनुसार प्रारंभिक स्वर, अलंकार एवं रागों के सफल समापन का प्रमाणपत्र',
      c2_title: 'सीनियर श्रेणी प्रमाणपत्र (Senior Category)',
      c2_desc: 'राग विस्तार, ताल प्रणाली, बंदिशें और सीनियर बोर्ड परीक्षा उत्तीर्ण करने की योग्यता',
      c3_title: 'विद्वत श्रेणी प्रमाणपत्र (Vidwath Category)',
      c3_desc: 'जटिल राग, बड़ा ख्याल, तराना और मंच प्रस्तुति में महारत का उच्च स्तरीय प्रमाणपत्र',
      c4_title: 'आधार षड्ज ट्रस्ट शिक्षण एवं मानद प्रमाणपत्र',
      c4_desc: 'भारतीय शास्त्रीय संगीत को दूसरों को सिखाने एवं प्रचार-प्रसार करने की योग्यता रखने वाले शिष्यों को ट्रस्ट सम्मान'
    },
    gallery: {
      title: 'गैलरी और मीडिया',
      subtitle: 'वृत्तचित्र, प्रस्तुतियां, मासिक बैठक एवं गुरुवंदना',
      viewFullBtn: 'पूरी गैलरी देखें →',
      exploreHeading: 'गुरुकुल के विशेष एवं ऐतिहासिक क्षण',
      documentaryTitle: 'आधार षड्ज गुरुकुल का वृत्तचित्र (डॉक्यूमेंट्री)',
      documentaryDesc: 'हिरेहड्डा में हमारे गुरुकुल की समृद्ध परंपरा एवं संगीतमय यात्रा का दृश्य',
      studentPerfTitle: 'छात्र द्वारा शास्त्रीय संगीत प्रस्तुति',
      studentPerfDesc: 'रागालाप और गायन प्रतिभा का प्रदर्शन करता गुरुकुल का शिष्य',
      teachingSessionTitle: 'गुरुकुल संगीत शिक्षण सत्र',
      teachingSessionDesc: 'पारंपरिक गुरु-शिष्य संगीत साधना एवं कक्षा का सजीव दृश्य',
      guruPerfTitle: 'श्री विनायक हेगड़े द्वारा शास्त्रीय गायन',
      guruPerfDesc: 'हिंदुस्तानी शास्त्रीय रागों की भावपूर्ण प्रस्तुति',
      baithakTitle: 'मासिक बैठक - संगीत सम्मेलन',
      baithakDesc: 'गुरुकुल में आयोजित होने वाली मासिक शास्त्रीय गायन एवं रियाज़ बैठक',
      guruvandanaTitle: 'गुरुवंदना उत्सव एवं सम्मान समारोह',
      guruvandanaDesc: 'पवित्र गुरु परंपरा को सादर नमन एवं सम्मान समारोह',
      studentConcertTitle: 'छात्र संगीत कार्यक्रम',
      traditionalPerfTitle: 'पारंपरिक गुरुकुल समारोह',
      uploadBtn: '+ फोटो / वीडियो अपलोड करें',
      filterAll: 'सभी मीडिया',
      filterDocumentary: 'वृत्तचित्र (डॉक्यूमेंट्री)',
      filterPerformances: 'गायन प्रस्तुतियां',
      filterTeaching: 'शिक्षण सत्र',
      filterBaithak: 'मासिक बैठक',
      filterGuruvandana: 'गुरुवंदना कार्यक्रम',
      filterUploaded: 'व्यवस्थापक अपलोड',
      uploadModalTitle: 'गैलरी में नई मीडिया जोड़ें (अधिकृत पहुँच)',
      mediaType: 'मीडिया प्रकार',
      typePhoto: 'फोटो (चित्र अपलोड)',
      typeVideo: 'यूट्यूब वीडियो',
      mediaTitle: 'शीर्षक *',
      mediaCategory: 'श्रेणी *',
      mediaDescription: 'विवरण',
      mediaYoutubeUrl: 'यूट्यूब लिंक (उदा. https://youtu.be/...)',
      mediaFile: 'चित्र फ़ाइल चुनें',
      submitUpload: 'गैलरी में जोड़ें',
      cancel: 'रद्द करें',
      backToHome: '← मुख्य पृष्ठ पर वापस जाएं',
      noItems: 'इस श्रेणी में कोई मीडिया नहीं मिला।',
      successUpload: 'मीडिया को सफलतापूर्वक गैलरी में जोड़ दिया गया!',
      authRequiredTitle: 'केवल अधिकृत व्यक्ति के लिए',
      authRequiredDesc: 'केवल अधिकृत आधार षड्ज व्यवस्थापक और गुरु ही मीडिया अपलोड या संशोधित कर सकते हैं।',
      enterPasscode: 'व्यवस्थापक पासकोड दर्ज करें',
      passcodePlaceholder: 'सुरक्षा पासकोड (Default: adhara@2024)',
      verifyLoginBtn: 'सत्यापित करें और अनलॉक करें',
      invalidPasscode: 'अमान्य पासकोड! कृपया अधिकृत व्यवस्थापक पासकोड दर्ज करें।',
      adminLoggedInBadge: 'अधिकृत व्यवस्थापक सक्रिय',
      logoutBtn: 'लॉग आउट',
      adminPasscodeHint: 'अनधिकृत अपलोड को रोकने के लिए व्यवस्थापक पासकोड आवश्यक है।'
    },
    registration: {
      title: 'छात्र पंजीकरण',
      subtitle: 'हमारे साथ अपनी संगीत यात्रा शुरू करें',
      firstName: 'पहला नाम *',
      lastName: 'अंतिम नाम *',
      email: 'ईमेल पता *',
      phone: 'फ़ोन नंबर *',
      age: 'आयु *',
      experience: 'पूर्व संगीत अनुभव / श्रेणी',
      expBeginner: 'जूनियर श्रेणी (Junior - नए सीखने वाले)',
      expIntermediate: 'सीनियर श्रेणी (Senior - 1-2 वर्ष का अनुभव)',
      expAdvanced: 'विद्वत श्रेणी (Vidwath - 3+ वर्ष का अनुभव)',
      selectCourse: 'श्रेणी / विधा चुनें *',
      address: 'पता *',
      city: 'शहर *',
      state: 'राज्य *',
      country: 'देश *',
      submitBtn: 'पंजीकरण जमा करें',
      submitting: 'जमा हो रहा है...',
      successMsg: 'पंजीकरण सफल रहा! हम कक्षा एवं बैच के विवरण के साथ शीघ्र ही आपसे संपर्क करेंगे।',
      placeholderName: 'आपका पहला नाम',
      placeholderLastName: 'आपका अंतिम नाम',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'आपका फ़ोन नंबर',
      placeholderAge: 'आपकी आयु',
      placeholderAddress: 'घर का पता',
      placeholderCity: 'शहर'
    },
    community: {
      title: 'हमारे समुदाय से जुड़ें',
      subtitle: 'संगीत प्रेमियों और शिक्षार्थियों से जुड़ें',
      intro: 'शास्त्रीय संगीत प्रेमियों, छात्रों और पेशेवरों के जीवंत समुदाय का हिस्सा बनें। अपने संगीत के प्रति जुनून को साझा करें और एक साथ आगे बढ़ें।',
      forums: 'ऑनलाइन मंच',
      forumsDesc: 'संगीत की अवधारणाओं पर चर्चा करें और साथी शिक्षार्थियों से सुझाव प्राप्त करें',
      events: 'नियमित कार्यक्रम',
      eventsDesc: 'प्रसिद्ध संगीतकारों द्वारा वर्चुअल कॉन्सर्ट, कार्यशालाएं और मास्टर क्लास',
      networking: 'नेटवर्किंग',
      networkingDesc: 'संगीत पेशेवरों और कलाकारों के साथ संबंध बनाएं',
      resources: 'संसाधन साझा करना',
      resourcesDesc: 'विशिष्ट शिक्षण सामग्री और रिकॉर्डिंग तक पहुंच',
      followUs: 'सोशल मीडिया पर हमें फॉलो करें',
      supportMission: 'हमारे मिशन का समर्थन करें',
      supportDesc: 'भारतीय शास्त्रीय संगीत परंपराओं को संरक्षित और प्रोत्साहित करने में हमारी सहायता करें',
      contributeBtn: 'अभी योगदान दें',
      processing: 'प्रक्रिया जारी है...'
    },
    reviews: {
      title: 'छात्रों की समीक्षाएं',
      subtitle: 'हमारे छात्र क्या कहते हैं',
      shareExperience: 'अपना अनुभव साझा करें',
      name: 'आपका नाम *',
      course: 'पाठ्यक्रम का नाम *',
      rating: 'रेटिंग *',
      reviewLabel: 'आपकी समीक्षा *',
      placeholderReview: 'आधार षड्ज के साथ अपने सीखने का अनुभव साझा करें...',
      submitReview: 'समीक्षा जमा करें',
      submittingReview: 'समीक्षा जमा हो रही है...',
      successReview: 'आपकी समीक्षा के लिए धन्यवाद! इसे जोड़ दिया गया है।',
      loadingReviews: 'समीक्षाएं लोड हो रही हैं...'
    },
    contact: {
      title: 'हमसे संपर्क करें',
      subtitle: 'आधार षड्ज गुरुकुल से संपर्क करें',
      phone: 'फ़ोन',
      phoneHours: 'उपलब्ध: सोम-शुक्र, 9AM-6PM IST',
      email: 'ईमेल',
      location: 'स्थान',
      locationPlace: 'हिरेहड्डा, उत्तर कन्नड़',
      locationState: 'कर्नाटक, भारत',
      nameLabel: 'नाम *',
      emailLabel: 'ईमेल *',
      phoneLabel: 'फ़ोन',
      subjectLabel: 'विषय *',
      messageLabel: 'संदेश *',
      placeholderName: 'आपका नाम',
      placeholderEmail: 'your@email.com',
      placeholderPhone: 'आपका फ़ोन नंबर',
      placeholderSubject: 'संगीत शिक्षण पूछताछ',
      placeholderMessage: 'अपनी रुचि और विधा (शास्त्रीय, भक्ति संगीत, ग़ज़ल, ठुमरी) के बारे में बताएं...',
      sendBtn: 'संदेश भेजें',
      sendingBtn: 'भेजा जा रहा है...',
      successMsg: 'संपर्क करने के लिए धन्यवाद! हम शीघ्र ही आपसे संपर्क करेंगे।'
    },
    footer: {
      aboutText: 'संरचित प्रशिक्षण और व्यक्तिगत मार्गदर्शन के माध्यम से भारतीय शास्त्रीय संगीत की परंपरा को संरक्षित और सिखाने के लिए समर्पित।',
      quickLinks: 'त्वरित लिंक',
      home: 'मुख्य पृष्ठ',
      aboutUs: 'हमारे बारे में',
      courses: 'श्रेणियां',
      contact: 'संपर्क',
      contactInfo: 'संपर्क जानकारी',
      followUs: 'सोशल मीडिया',
      rights: 'सर्वाधिकार सुरक्षित।'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('adhara_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('adhara_language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (path) => {
    const keys = path.split('.');
    let current = translations[language];
    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key];
      } else {
        // Fallback to English
        let fallback = translations['en'];
        for (const fKey of keys) {
          if (fallback && fallback[fKey] !== undefined) {
            fallback = fallback[fKey];
          } else {
            return path;
          }
        }
        return fallback;
      }
    }
    return current;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
